### ISSUE TITLE
Spaces in path will cause issues

### ISSUE THREAD

**Issue by Kaitou-3D** [mushroom-guy/mwb-materials#4]
If there is a space in the file path, vtfs will fail to be created and the vmt will be malformed. 
![image](https://user-images.githubusercontent.com/26198203/224586099-f20bd223-1cdb-48fd-affd-2d6a73a57b73.png)

**Comment by mushroom-guy** [comment]
problem with vtfcmd. still have to figure out how to work around that :(

**Comment by Kaitou-3D** [comment]
An idea of the top of my head: you could keep a copy of the original path, and make a new path with '_' for every space to send to vtfcmd, and then do a search & replace the new path with the original after you're done. It would be ham-fisted, but it might work if _ is a valid character

**Comment by Kaitou-3D** [comment]
In the interim, I think it would be wise to check the path for spaces( and any other invalid character), and error out with a warning to the user instructing them that the path is malformed
