### ISSUE TITLE
Textures Generated but not generated

### ISSUE THREAD

**Issue by SmokyRoses** [mushroom-guy/mwb-materials#5]
So Recently I opened MWB materials and clicked open folder as I selected a folder with pngs in it and clicked ok or whatever, It said generated textures but HOWEVER, it only creates VMT (output) but not temp folder which I suppose it's textures folder, simply generated VTFs doesn't show and I'm losing my mind of it, In some cases it'd create temp folder but tool would crash and yeah, I hope there's solution, is there anything I need like runtime or something?

**Comment by One-Trick-Viper** [comment]
you probably have spaces in your path, make sure there are no spaces in both paths.
